name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  # This is the destination directory for CPM tool
  USERPROFILE: .
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:      
      - name: Get CPM
        uses: engineerd/configurator@v0.0.10
        with:
          name: cpm.exe
          url: https://github.com/neacsum/cpm/releases/latest/download/cpm.exe
      
      - name: Clone
        run: git clone https://github.com/neacsum/example_super_app.git .\super_app

      - name: Build
        run: cpm -v --proto https -r . super_app
        
      - name: Run app
        run: .\super_app\build\app\x64\Debug\super_app.exe
