name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  USERPROFILE: .
  DEV_ROOT: .
  BUILD_CONFIGURATION: Release
  MACHINE: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - run: mkdir .ssh
      - run: echo github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl >.ssh/known_hosts
      
      - name: Get CPM
        uses: engineerd/configurator@v0.0.8
        with:
          name: cpm.exe
          url: https://github.com/neacsum/cpm/releases/latest/download/cpm.exe
      
      - name: Build
        run: cpm
        
