name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  USERPROFILE: .
  DEV_ROOT: .
  BUILD_CONFIGURATION: Release
  MACHINE: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get CPM
        uses: engineerd/configurator@v0.0.8
        with:
          name: cpm.exe
          url: https://github.com/neacsum/cpm/releases/latest/download/cpm.exe
      
      - name: Clone
        run: git clone https://github.com/neacsum/example_super_app.git .\super_app
        
      - name: Build
        run: cpm super_app
        
