name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  # This is the destination directory for CPM tool
  USERPROFILE: $HOME
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:      
      - name: Get CPM
        uses: engineerd/configurator@v0.0.10
        with:
          name: cpm.exe
          url: https://github.com/neacsum/cpm/releases/latest/download/cpm.exe
      
      - name: Build
        run: cpm -v --proto https -u https://github.com/neacsum/example_super_app -r . super_app
        
      - name: Run app
        run: .\super_app\build\x64\bin\Debug\super_app.exe
